version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-aiqfome
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-aiqfome
    ports:
      - '6379:6379'
